version: 2.1
workflows:
    lint_and_test:
        jobs:
            - lint
            - core-test
            - core-cli-test
            - backend-test
            - frontend-test
            - frontend-e2e-test
            - circuits-test
            - staging-deploy:
                  context: cloudflare
                  filters:
                      branches:
                          only:
                              - main

# Just for reusing below
step_defs:
    - run: &node_version
          name: Set Node version
          command: |
              nvm install v16
              nvm alias default v16
              echo "nvm use default" >> $BASH_ENV
    - run: &check_version
          name: Check Node version
          command: node -v | grep v16

jobs:
    lint:
        machine:
            image: ubuntu-2204:2022.04.1
        resource_class: medium
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install
                  command: yarn
            - run:
                  name: Lint
                  command: yarn lint --check
    core-test:
        resource_class: large
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install Packages
                  command: yarn
            - run:
                  name: Build
                  command: yarn build --scope @unirep-social/circuits --scope @unirep-social/core
            - run:
                  name: Test
                  command: cd packages/core && yarn test --parallel
    core-cli-test:
        resource_class: large
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install Packages
                  command: yarn
            - run:
                  name: Build
                  command: yarn build --scope @unirep-social/circuits --scope @unirep-social/core
            - run:
                  name: Test
                  command: cd packages/core && yarn test-cli
    backend-test:
        resource_class: large
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install Packages
                  command: yarn
            - run:
                  name: Build
                  command: yarn build --scope @unirep-social/circuits --scope @unirep-social/core --scope @unirep-social/backend
            - run:
                  name: Test
                  command: cd packages/backend && yarn test
    frontend-test:
        resource_class: medium
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install Packages
                  command: yarn
            - run:
                  name: Build
                  command: yarn build --scope @unirep-social/circuits --scope @unirep-social/core --scope @unirep-social/frontend
            - run:
                  name: Test
                  command: cd packages/frontend && yarn test
    frontend-e2e-test:
        resource_class: medium
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install Packages
                  command: yarn
            - run:
                  name: Build
                  command: yarn build --scope @unirep-social/circuits --scope @unirep-social/core --scope @unirep-social/frontend
            - run:
                  name: E2E Test
                  command: cd packages/frontend && yarn test:e2e
    circuits-test:
        resource_class: medium
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install Packages
                  command: yarn && yarn bootstrap --force-local
            - run:
                  name: Build
                  command: yarn build --scope @unirep-social/circuits
            - run:
                  name: Test
                  command: cd packages/circuits && yarn test
    staging-deploy:
        resource_class: medium
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install Packages
                  command: yarn && yarn bootstrap --force-local
            - run:
                  name: Build
                  command: |
                      yarn build --scope @unirep-social/circuits --scope @unirep-social/core
                      cd packages/frontend
                      echo "export default {DEFAULT_ETH_PROVIDER_URL: 'wss://opt-goerli.g.alchemy.com/v2/jmUZpyZefDikb3q-mL3W1VOwbEKM-DKN', SERVER:'https://unirep.social'}" > src/localConfig.ts
                      yarn build --mode production
                      yarn build:worker
            - run:
                  name: Deploy
                  command: |
                      cd packages/frontend
                      npx wrangler publish
