version: 2.1
workflows:
    lint_and_test:
        jobs:
            - lint
            - core-test
            - core-cli-test
            - backend-test
            - frontend-test

# Just for reusing below
step_defs:
    - run: &node_version
          name: Set Node version
          command: |
              nvm install v14
              nvm alias default v14
              echo "nvm use default" >> $BASH_ENV
    - run: &check_version
          name: Check Node version
          command: node -v | grep v14

jobs:
    lint:
        machine:
            image: ubuntu-2204:2022.04.1
        resource_class: medium
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install
                  command: yarn
            - run:
                  name: Lint
                  command: yarn lint --check
    core-test:
        resource_class: large
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install Packages
                  command: yarn && yarn bootstrap --force-local
            - run:
                  name: Build
                  command: yarn build
            - run:
                  name: Test
                  command: cd packages/core && yarn test
    core-cli-test:
        resource_class: large
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install Packages
                  command: yarn && yarn bootstrap --force-local
            - run:
                  name: Build
                  command: yarn build
            - run:
                  name: Test
                  command: cd packages/core && yarn test-cli
    backend-test:
        resource_class: large
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install Packages
                  command: yarn && yarn bootstrap --force-local
            - run:
                  name: Build
                  command: yarn build
            - run:
                  name: Test
                  command: cd packages/backend && yarn test
    frontend-test:
        resource_class: medium
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install Packages
                  command: yarn && yarn bootstrap --force-local
            - run:
                  name: Build
                  command: yarn build
            - run:
                  name: Test
                  command: cd packages/frontend && yarn test
