version: 2.1
workflows:
    lint_and_test:
        jobs:
            - lint
            - build
            - core-test:
                  requires:
                      - build
            - backend-test:
                  requires:
                      - build
            - frontend-test:
                  requires:
                      - build
            - frontend-e2e-test:
                  requires:
                      - build
            - circuits-test:
                  requires:
                      - build
            - staging-deploy:
                  context: cloudflare
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - main

# Just for reusing below
step_defs:
    - run: &node_version
          name: Set Node version
          command: |
              nvm install v16
              nvm alias default v16
              echo "nvm use default" >> $BASH_ENV
    - run: &check_version
          name: Check Node version
          command: node -v | grep v16
    - run: &install_circom
          name: Install Circom
          command: |
              curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
              source "$HOME/.cargo/env"
              cd /tmp
              git clone https://github.com/iden3/circom.git
              cd circom
              cargo build --release
              cargo install --path circom

jobs:
    build:
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run: *node_version
            - run: *check_version
            - run: *install_circom
            - run:
                  name: Install Packages
                  command: yarn
            - run:
                  name: Build
                  command: yarn build
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - node_modules
                      - packages/circuits/zksnarkBuild
                      - packages/circuits/dist
                      - packages/core/artifacts
                      - packages/core/build
                      - packages/core/typechain
                      - packages/core/contracts
                      - packages/frontend/build
                      - packages/backend/build
                      - packages/backend/keys
    lint:
        machine:
            image: ubuntu-2204:2022.04.1
        resource_class: medium
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install
                  command: yarn
            - run:
                  name: Lint
                  command: yarn lint:check
    core-test:
        resource_class: large
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run: *node_version
            - run: *check_version
            - run:
                  name: Core Test
                  command: yarn core test
    backend-test:
        resource_class: large
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run: *node_version
            - run: *check_version
            - run:
                  name: Backend Test
                  command: yarn backend test
    frontend-test:
        resource_class: medium
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run: *node_version
            - run: *check_version
            - run:
                  name: Frontend Test
                  command: yarn frontend test
    frontend-e2e-test:
        resource_class: medium
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run: *node_version
            - run: *check_version
            - run:
                  name: E2e Test
                  command: yarn frontend test:e2e
    circuits-test:
        resource_class: medium
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run: *node_version
            - run: *check_version
            - run:
                  name: Circuit Test
                  command: yarn circuits test
    staging-deploy:
        resource_class: medium
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install Packages
                  command: yarn bootstrap --force-local
            - run:
                  name: Build
                  command: |
                      cd packages/frontend
                      echo "export default {DEFAULT_ETH_PROVIDER_URL: 'https://opt-goerli.g.alchemy.com/v2/3DDbMgNQZwgrzVl1mhaVqN3zog5OZpAU', SERVER:'https://api.unirep.social'}" > src/localConfig.ts
                      yarn build --mode production
                      yarn build:worker
            - run:
                  name: Deploy
                  command: |
                      cd packages/frontend
                      npx wrangler publish
